name: Documentation Deployment

on:
  push:
    branches:
      - main  # Only trigger on changes to the main branch
    paths:
      - "docs/api/*.md"  # Only trigger when files inside docs/api/ change

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install MkDocs
        run: pip install mkdocs mkdocs-material

      - name: Build and Deploy Documentation
        run: mkdocs gh-deploy --force
