name: Deploy to ReadTheDocs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install mkdocs
        run: pip install mkdocs mkdocs-material

      - name: Deploy Docs
        run: mkdocs gh-deploy --force
