name: Test Workflow

on:
  push:
    paths:
      - 'hello.py'  # Runs only if hello.py is modified
    branches:
      - master  # Change to 'main' if needed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Print Test Message
        run: echo "Hello, GitHub Actions!"
